name: Test CI

'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
      
jobs:
  build-and-test:
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-tags: 'true'
          fetch-depth: '0'
          
      - name: Test NVMF
        # run: exec timeout 1h launch-test.sh
        # run: exec ~/bin/launch-test.sh
        run: env
        run: exec ls
        
      - name: Archive Test Output
        uses: actions/upload-artifact@v4
        with:
          name: nvmf-test-output
          path: ~/test-from-sh/output.tar
