name: Makefile CI

'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master
jobs:
  build:
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-tags: 'true'
          fetch-depth: '0'
      - name: Test NVMF
        run: ~/spdk-community-ci/ci-helper/launch-test.sh
      - name: Archive Test Output
        uses: actions/upload-artifact@v4
        with:
          name: nvmf-test-output
          path: /home/vagrant/test-from-sh/output.tar
